export const CURSOR_HOVERED_SAGA = "CURSOR_HOVERED_SAGA";
export const CURSOR_HOVERED = "CURSOR_HOVERED";
export const CURSOR_POINTER_SAGA = "CUROSR_POINTER_SAGA";
export const CURSOR_POINTER = "CURSOR_POINTER";

export const ON_TRANSITION_SAGA = "ON_TRANSITION_SAGA";
export const OFF_TRANSITION_SAGA = "OFF_TRANSITION_SAGA";
export const ON_TRANSITION = "ON_TRANSITION";
export const OFF_TRANSITION = "OFF_TRANSITION";
