export const CURSOR_HOVERED_SAGA = "CURSOR_HOVERED_SAGA";
export const CURSOR_HOVERED = "CURSOR_HOVERED";
export const CURSOR_POINTER_SAGA = "CUROSR_POINTER_SAGA";
export const CURSOR_POINTER = "CURSOR_POINTER";
